### ISSUE TITLE
Issue in following the README for handling incoming requests in the AppDelegate

### ISSUE THREAD

**Issue by fabiomassimo** [delba/SwiftyOAuth#11]
From the docs:

```
Step 2: Handle the incoming requests

Handle the incoming requests in your AppDelegate:

func application(app: UIApplication, openURL url: NSURL, options: [String : AnyObject]) -> Bool {
    github.handleURL(url, options: options)

    return true
}
```

Unfortunately, while I was following the README, I found out that that the delegate method signature is slightly different:

``` swift
func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool
```

This causes an inconsistency with the designated method to handle an URL from the Provider.

``` swift
    /**
     Handles the incoming URL.

     - parameter URL:     The incoming URL to handle.
     - parameter options: A dictionary of launch options.
     */
    public func handleURL(URL: NSURL, options: [String : AnyObject])
```

I think it should be rewritten in something like:

``` swift
public func handleURL(URL: NSURL, sourceApplication: String?) 
```

Such that the _Step 2_ from the README would look like:

``` swift
func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {
    github.handleURL(url, sourceApplication: sourceApplication)

    return true
}
```

**Comment by delba** [comment]
`func application(app: UIApplication, openURL url: NSURL, options: [String : AnyObject])` is available in iOS 9 and the other ones are deprecated.

Since I plan to drop the support for iOS8 when iOS10 is released, I think it's better to leave it like that.

**Comment by delba** [comment]
@fabiomassimo I changed my mind, I'm gonna support both 😄 

I'm gonna do it unless you want to?

**Comment by fabiomassimo** [comment]
On it :)

**Comment by delba** [comment]
Ahaha me too

I'm almost done :)

**Comment by fabiomassimo** [comment]
Hahahaha ok I'll step back.

**Comment by delba** [comment]
It took me way longer than expected but here it is: f2b743aabb03d67b9e723646efdd52aae630ac4b

**Comment by delba** [comment]
Also I encounter a problem when testing on iOS 8.

 `UIApplicationDidBecomeActiveNotification` is called before `application:openURL:sourceApplication:annotation:` and thus the completion block is called twice. First with `Failure(.Cancel)` and next with `Success(token)`.

It's maybe because I tested it in the simulator (?)
