### ISSUE TITLE
Xcode 8 GM

### ISSUE THREAD

**Issue by damianesteban** [delba/SwiftyOAuth#17]
Does anyone have SwiftyOAuth working with the Xcode 8 GM?  I marked the completion blocks in `Provider` as `@escaping` where necessary and it is building fine but the issue now is that the new method in the `AppDelegate` to open urls now has the following signature:

```
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool
```

so the `Provider` method `handleURL` is not working.

Great library by the way.  It's nice and lightweight and has the `Result` type built-in.  SwiftyOAuth is definitely going to be my default OAuth library from now on.

**Comment by delba** [comment]
Hi @damianesteban, thanks for the kind words!

Check out the [`swift-3.0`](https://github.com/delba/SwiftyOAuth/tree/swift-3.0) branch to use SwiftyOAuth with Xcode 8 GM. It's gonna be the `master` branch after the official release.
Also, I just updated the `handleURL(_:options:)` signature thanks to your heads up :)

Thanks again!
