### ISSUE TITLE
Instagram does not supply token_type and the flow breaks

### ISSUE THREAD

**Issue by radianttap** [delba/SwiftyOAuth#2]
In Token.swift, this init makes the all 3 parameters mandatory:

```
        guard let
            accessToken = json["access_token"] as? String,
            tokenType = json["token_type"] as? String,
            scope = json["scope"] as? String
        else { return nil }
```

However, Instagram only returns access_token

```
{
    "access_token": "2342264381.bc3c943.6086017a221b427a997e4928f0ea197b",
    "user": {
...
    }
}
```

What do you think about this:

```
    internal init?(json: JSON) {
        guard let
            accessToken = json["access_token"] as? String
        else { return nil }

        self.accessToken = accessToken

        self.tokenType = json["token_type"] as? String ?? ""
        self.scope = json["scope"] as? String ?? ""

        self.dictionary = json
    }
```

**Comment by delba** [comment]
Hi @radianttap , thanks for the issue!

I don't know which version you are using but Instagram is supposed to use `init?(fragments: [String: String])` [L45](https://github.com/delba/SwiftyOAuth/blob/v0.2/Source/Token.swift#L45) in `v0.2` (the version in which Instagram has been introduced).

Also check out the master branch, I would be interested in having some feedback 😃

**Comment by delba** [comment]
Also note that Instagram is using the client-side flow. So:

`http://your-redirect-uri#access_token=ACCESS-TOKEN` 

At the very bottom of their [doc page](https://www.instagram.com/developer/authentication/)

**Comment by radianttap** [comment]
Instagram can use both server and client side flow.

I used 0.1, implemented it about 2 days ago :)
Over the weekend I tried 4 different OAuth wrappers for Swift and like yours the best, which is why I used it to implement this Instagram wrapper I'm working on. I'll certainly follow along and supply pull requests as I do something useful.

**Comment by delba** [comment]
The SwiftyOAuth Instagram provider only uses the client-side flow https://github.com/delba/SwiftyOAuth/blob/master/Source/Providers/Instagram.swift

Yes please do supply PR :)

**Comment by delba** [comment]
Hey @radianttap , I just pushed the `v0.3` which is (quite a) big update. I would love to hear your feedback if you find the time :)

In addition to the ability of refreshing token (which doesn't concern `Instagram` though), here are the changes:

``` swift
instagram.scopes = ["some", "scope", "here"] // instead of instagram.scope = "some scope here"
instagram.token // return Token?
```

The additional request params have been renamed and now are `[String: String]`:

``` swift
instagram.additionalAuthRequestParams
instagram.additionalTokenRequestParams
```

Let me know what you think!

**Comment by radianttap** [comment]
Will do, although I finished what I needed - it was a demo project to teach API wrappers

Will certainly let you know when I get around it. Right now - preparing for WWDC labs :)

**Comment by delba** [comment]
Awesome, thanks!

Btw, since the `v0.3.2`, you're able to use the server-side (explicit) flow for Instagram  :)

Have a good time at the WWDC!!
