### ISSUE TITLE
Compiler Errors

### ISSUE THREAD

**Issue by gtokman** [delba/SwiftyOAuth#25]
I am receiving many compiler errors when integrating into a basic Swift 3 application with cocoa pods. 

```
pod 'SwiftyOAuth', '~> 0.3' // the pod 
```

<img width="258" alt="screen shot 2017-02-27 at 12 40 03 pm" src="https://cloud.githubusercontent.com/assets/12258850/23372612/3d7777f4-fcea-11e6-9c05-882d354d7995.png">

**Comment by delba** [comment]
Hi @gtokman, you have to install `1.1` (I just updated the README). Thanks!
