### ISSUE TITLE
How to resolve view is not in window hierarchy error?

### ISSUE THREAD

**Issue by udayathreya** [delba/SwiftyOAuth#28]
Attempt to present <SFSafariViewController: 0x7fc7ba018400> on <MyOauth.ViewController: 0x7fc7b860b070> whose view is not in the window hierarchy!

**Comment by delba** [comment]
Hi @udayathreya, where did you call the `authorize` method ? Make sure the `MyOauth.ViewController`'s view is already in the view hierarchy before making this call.
