### ISSUE TITLE
Multi platform support

### ISSUE THREAD

**Issue by fabiomassimo** [delba/SwiftyOAuth#8]
The OAuth Authentication process nowadays can be triggered from many devices equipped with different os: watch OS, iOS, tvOS.

Unfortunately, not all of this operating system can rely on a safe way to implement the OAuth 2.0 authentication flow: 
- tvOS does not support `SafariServices` or Webkit.
- watchOS does not support `SafariServices` or Webkit.
- Today extension can not present webpages.

My idea to address this issue would be to implement for `SwiftyOAuth` following goals:
- [ ] Make the library use app extension API only. 
- [ ] Add support for multiple platform: iOS, watchOS, tvOS.
- [ ]  Improve `-authorize` method depending on current platform and capabilities.

What do you think?

**Comment by delba** [comment]
Multi-platform support is **definitely** on the roadmap!

But I first want to make it very good on iOS before thinking about all the compatibility issues.
Here is my roadmap:
- [ ] Store the token in the `KeyChain` (it will be the default instead of the current `NSUserDefaults`)
- [ ] Add an option to present a `WKWebView` instead of `SFSafariViewController` / open Safari mobile

Some providers (like LinkedIn) don't accept app links and the only way to use OAuth is to handle the incoming URLs in `webView(_:decidePolicyForNavigationAction:decisionHandler:)`

**Comment by delba** [comment]
I'm started working on the `WKWebView` stuff btw.

The API will probably look like:

``` swift
provider.useWebView = true
```

**Comment by fabiomassimo** [comment]
Great,
I'm working on a separate branch on my repo for the multi platform support since I really think this is a required feature. Maybe later on you can give a look to see how it looks.

As I see from your roadmap I'd be more than happy to work on the keychain support.

Do you agree to use as dependency one of the library already available to access the keychain? I think this can help the development process and the library would have everything set to install dependencies for testing purposes too.

Sorry we are definitely going out of topic here. I can start a new issue to discuss this.

**Comment by delba** [comment]
> As I see from your roadmap I'd be more than happy to work on the keychain support.

You would be a life savior!!!

> Do you agree to use as dependency one of the library already available to access the keychain?

No :/

We only need to set/get a dictionary in the KeyChain. It's really a pain to work with it, I know, but adding a dependency just for that is a bit too much...

I'm gonna keep a eye on your fork! Thanks a lot !! 🙏

**Comment by fabiomassimo** [comment]
> I'm started working on the WKWebView stuff btw.

To pave the way for the multi platform support it would be great to remove call to `openURL` method from `UIApplication` Class

**Comment by delba** [comment]
I pushed the [`next`](https://github.com/delba/SwiftyOAuth/tree/next) branch with the WebView thing (WIP) if you want to take a stab :)

**Comment by fabiomassimo** [comment]
💯 

Next thing is to remove the reference to `UIApplication` to present the `WKWebview` or the `SafariViewController`.

Maybe the `authorize` can take as parameter an `hostViewController`? 🤔

**Comment by delba** [comment]
> Next thing is to remove the reference to UIApplication to present the WKWebview or the SafariViewController.

Why?

> Maybe the authorize can take as parameter an hostViewController?

No, all the configuration (`useWebView`, `additionalParams`, etc) should be in only one place

**Comment by fabiomassimo** [comment]
By having in mind to support multi platform one day  `UIApplication.sharedApplication()` is not an allowed API.

**Comment by delba** [comment]
We'll see when this day comes
